#!/usr/bin/env bash
# holography bootstrap.sh — install the agent framework into any project
# No npm required. Run from your project root.
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/SalDevX/holography/main/bootstrap.sh | bash
#   OR: bash tools/agent-framework/tools/bootstrap.sh
#
# What it does:
#   1. Detects project structure
#   2. Scaffolds agents/, memory/, bin/, logs/, docs/setup/
#   3. Copies template files with PROJECT_NAME substituted
#   4. Installs post-commit hook
#   5. Runs graphify if installed
#   6. Prints next steps

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

FRAMEWORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(pwd)"
PROJECT_NAME="$(basename "$PROJECT_ROOT")"
DATE="$(date +%Y-%m-%d)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[holography]${NC} $*"; }
warn() { echo -e "${YELLOW}[holography] warn:${NC} $*"; }
err()  { echo -e "${RED}[holography] error:${NC} $*"; exit 1; }

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

log "Installing holography into: $PROJECT_ROOT"
log "Project name: $PROJECT_NAME"

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    warn "No .git directory found. Post-commit hook will not be installed."
    warn "Run 'git init' first if you want automatic memory updates."
fi

# ---------------------------------------------------------------------------
# Step 1 — Create directory structure
# ---------------------------------------------------------------------------

log "Step 1/7 — Creating directory structure..."
mkdir -p \
    "$PROJECT_ROOT/agents" \
    "$PROJECT_ROOT/memory" \
    "$PROJECT_ROOT/bin" \
    "$PROJECT_ROOT/logs" \
    "$PROJECT_ROOT/tests" \
    "$PROJECT_ROOT/tools" \
    "$PROJECT_ROOT/docs/setup"

log "  agents/ memory/ bin/ logs/ tests/ tools/ docs/setup/ — created"

# ---------------------------------------------------------------------------
# Step 2 — Copy and substitute templates
# ---------------------------------------------------------------------------

log "Step 2/7 — Copying templates..."

_render() {
    local src="$1" dst="$2"
    sed \
        -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
        -e "s/{{DATE}}/$DATE/g" \
        "$src" > "$dst"
    log "  $dst"
}

# Core files (only if not already present)
[ ! -f "$PROJECT_ROOT/CLAUDE.md" ] && \
    _render "$FRAMEWORK_DIR/templates/CLAUDE.md" "$PROJECT_ROOT/CLAUDE.md"

[ ! -f "$PROJECT_ROOT/AGENTS.md" ] && \
    _render "$FRAMEWORK_DIR/templates/AGENTS.md" "$PROJECT_ROOT/AGENTS.md"

[ ! -f "$PROJECT_ROOT/memory/MEMORY.md" ] && \
    _render "$FRAMEWORK_DIR/templates/MEMORY.md" "$PROJECT_ROOT/memory/MEMORY.md"

[ ! -f "$PROJECT_ROOT/memory/MEMORY_MAP.md" ] && \
    _render "$FRAMEWORK_DIR/templates/MEMORY_MAP.md" "$PROJECT_ROOT/memory/MEMORY_MAP.md"

# Agent prompts
for prompt in dispatcher validator meta-controller memory-keeper \
              framework-auditor memory-bootstrapper stack-detector god-node-hunter; do
    src="$FRAMEWORK_DIR/templates/agents/${prompt}.prompt"
    dst="$PROJECT_ROOT/agents/${prompt}.prompt"
    [ -f "$src" ] && [ ! -f "$dst" ] && _render "$src" "$dst"
done

# Copy domain-agent example
[ ! -f "$PROJECT_ROOT/agents/domain-agent.prompt.example" ] && \
    cp "$FRAMEWORK_DIR/templates/agents/domain-agent.prompt.example" \
       "$PROJECT_ROOT/agents/domain-agent.prompt.example"

# ---------------------------------------------------------------------------
# Step 3 — Copy tools
# ---------------------------------------------------------------------------

log "Step 3/7 — Installing tools..."

[ ! -f "$PROJECT_ROOT/tools/validator.py" ] && \
    cp "$FRAMEWORK_DIR/tools/validator.py" "$PROJECT_ROOT/tools/validator.py" && \
    log "  tools/validator.py"

[ ! -f "$PROJECT_ROOT/tools/meta_controller.py" ] && \
    cp "$FRAMEWORK_DIR/tools/meta_controller.py" "$PROJECT_ROOT/tools/meta_controller.py" && \
    log "  tools/meta_controller.py"

# ---------------------------------------------------------------------------
# Step 4 — Install bin/meta-controller
# ---------------------------------------------------------------------------

log "Step 4/7 — Installing bin/meta-controller..."
if [ ! -f "$PROJECT_ROOT/bin/meta-controller" ]; then
    cat > "$PROJECT_ROOT/bin/meta-controller" << 'BINEOF'
#!/usr/bin/env python3
"""
bin/meta-controller — agent retry loop entry point
Generated by holography bootstrap.sh

Usage:
    bin/meta-controller --task "your task description"
    echo "task" | bin/meta-controller
    bin/meta-controller --task "task" --dry-run
"""
import argparse, json, os, re, subprocess, sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
from tools.meta_controller import FailBlock, MetaController

def log_info(msg): print(f"[INFO] {msg}", flush=True)
def log_warn(msg): print(f"[WARN] {msg}", file=sys.stderr, flush=True)

def run_agent(task, patches, params):
    env = os.environ.copy()
    model = params.get("_model_override")
    if model == "human":
        log_warn("[meta-controller] human escalation required")
        return ""
    env_p = {k: v for k, v in params.items() if k != "_model_override"}
    if env_p: env["META_PARAM_PATCH"] = json.dumps(env_p)
    patched = task + ("\n" + "\n".join(f"[constraint] {p}" for p in patches) if patches else "")
    try:
        cmd = ["claude", "-p", "--dangerously-skip-permissions", patched]
        if model: cmd += ["--model", model]
        r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=180, cwd=str(PROJECT_ROOT))
        return r.stdout if r.returncode == 0 else ""
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return ""

def run_validator(output):
    if not output: return False, "empty output", None
    has_diff = any(l.startswith("diff --git") for l in output.splitlines()) and "@@" in output
    if not has_diff: return False, "no-diff-output", None
    r = subprocess.run([sys.executable, str(PROJECT_ROOT / "tools" / "validator.py")],
        input=output, capture_output=True, text=True, cwd=str(PROJECT_ROOT), timeout=30)
    raw = (r.stdout + r.stderr).strip()
    passed = "STATUS: PASS" in raw and r.returncode == 0
    m = re.search(r"RETRY_WITH:\s*(\S+)", raw)
    retry = m.group(1) if m and m.group(1) not in ("none", "None") else None
    return passed, ("" if passed else raw), retry

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--task", default="")
    p.add_argument("--fail-block", default="")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    task = args.task or (sys.stdin.read().strip() if not sys.stdin.isatty() else "")
    if not task:
        print("ERROR: provide task via --task or stdin", file=sys.stderr); return 2
    if args.dry_run:
        fb = FailBlock.from_text(args.fail_block or "FAIL:\n  category: parity\n  signal: dry run", attempt=1)
        mc = MetaController(task=task)
        for attempt in range(2, 4):
            plan = mc.build_retry_plan_for_attempt(fb, attempt)
            print(f"--- Attempt {attempt} ---\n{json.dumps(plan.as_dict(), indent=2)}\n")
        return 0
    fb = FailBlock.from_text(args.fail_block, attempt=1) if args.fail_block else None
    mc = MetaController(task=task, initial_fail_block=fb)
    result = mc.run(agent_runner=run_agent, validator=run_validator)
    if result["passed"]:
        log_info(f"PASS in {result['attempts']} attempt(s)"); return 0
    log_warn(f"ESCALATE after {result['attempts']} attempts — {result.get('report_path', '')}"); return 1

if __name__ == "__main__": sys.exit(main())
BINEOF
    chmod +x "$PROJECT_ROOT/bin/meta-controller"
    log "  bin/meta-controller"
fi

# ---------------------------------------------------------------------------
# Step 5 — Install post-commit hook
# ---------------------------------------------------------------------------

log "Step 5/7 — Installing post-commit hook..."
if [ -d "$PROJECT_ROOT/.git" ]; then
    cat > "$PROJECT_ROOT/.git/hooks/post-commit" << HOOKEOF
#!/bin/bash
cd "\$(git rev-parse --show-toplevel)"
command -v claude &> /dev/null || { echo "[memory-keeper] claude not found — skipping"; exit 0; }
echo "[memory-keeper] updating agent knowledge from commit..."
claude --dangerously-skip-permissions \
    "You are @memory-keeper. Read agents/memory-keeper.prompt.
     Run: git diff HEAD~1 HEAD --name-only && git log -1 --format='%s %b'
     Read graphify-out/GRAPH_REPORT.md if it exists.
     Update memory/MEMORY.md Recent Fixes. Update memory/MEMORY_MAP.md if new functions added.
     Update relevant agents/*.prompt if new files added. Run graphify update . last.
     Be specific. No prose." 2>&1 | tee -a logs/memory-keeper.log
echo "[memory-keeper] done"
HOOKEOF
    chmod +x "$PROJECT_ROOT/.git/hooks/post-commit"
    log "  .git/hooks/post-commit — installed"
else
    warn "  skipped (no .git directory)"
fi

# ---------------------------------------------------------------------------
# Step 6 — Run graphify
# ---------------------------------------------------------------------------

log "Step 6/7 — Running graphify..."
if command -v graphify &> /dev/null; then
    cd "$PROJECT_ROOT" && graphify update . 2>&1 | tail -2
    log "  graphify-out/ updated"
else
    warn "  graphify not found. Install: pip install graphify-cli"
    warn "  Then run: graphify update ."
fi

# ---------------------------------------------------------------------------
# Step 7 — Summary
# ---------------------------------------------------------------------------

log "Step 7/7 — Done."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  holography installed in: $PROJECT_ROOT"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Run the bootstrap agents in Claude Code:"
echo "     /stack-detector    — configure routing table"
echo "     /framework-auditor — map all files and functions"
echo "     /god-node-hunter   — identify god nodes"
echo "     /memory-bootstrapper — fill MEMORY.md interactively"
echo ""
echo "  2. Verify smoke tests pass:"
echo "     python3 -m pytest tests/smoke_test.py -v"
echo ""
echo "  3. Commit the agent system:"
echo "     git add agents/ memory/ CLAUDE.md AGENTS.md bin/ tools/validator.py"
echo "     git add tools/meta_controller.py docs/setup/"
echo "     git commit -m 'feat: install holography framework'"
echo ""
echo "  4. Open the project in Claude Code — it will read CLAUDE.md"
echo "     and start routing through the agent system immediately."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
